services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    networks:
      - web-net
    environment:
      DOMAIN: "https://vault.matheuslp.com"
      SIGNUPS_ALLOWED: "false"
    volumes:
      - data:/data/

networks:
  web-net:
    external: true

volumes:
  data:
