name: paperless

services:
  broker:
    image: docker.io/valkey/valkey:9-alpine
    restart: unless-stopped
    volumes:
      - redisdata:/data
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-ngx
    networks:
      - default
      - web-net
    restart: unless-stopped
    depends_on:
      - broker
      - gotenberg
      - tika
    # ports:
    #   - "8000:8000"
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - export:/usr/src/paperless/export
      - consume:/usr/src/paperless/consume
    env_file: .env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBENGINE: sqlite
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_APPS: 'allauth.socialaccount.providers.openid_connect'
      PAPERLESS_SOCIALACCOUNT_PROVIDERS: '{"openid_connect":{"SCOPE":["openid","profile","email"],"OAUTH_PKCE_ENABLED":true,"APPS":[{"provider_id":"authelia","name":"Authelia","client_id":"vf3NBlj-qnLx95LplpdEiljPrbOaCYs1oMvIgZW72UFOUR0EwhWT9BOw9gpxc-st3VLA~QTI","secret":"${OIDC_CLIENT_SECRET:?error}","settings":{"server_url":"https://auth.matheuslp.com","token_auth_method":"client_secret_basic"}}]}}'
      PAPERLESS_DISABLE_REGULAR_LOGIN: true
      PAPERLESS_REDIRECT_LOGIN_TO_SSO: true
  gotenberg:
    image: docker.io/gotenberg/gotenberg:8.34
    restart: unless-stopped
    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
  tika:
    image: docker.io/apache/tika:latest
    restart: unless-stopped
volumes:
  data:
  media:
  export:
  consume:
  redisdata:

networks:
  web-net:
    external: true
